export const projects = [
  {
    img: "https://github.com/Swapnil1296/portfolio_images/blob/main/images/c2c.png?raw=true",
    title: "Connect2Clinic",
    des: "Connect2Clinic, an exceptional digital initiative pioneered by Alkem Labs, is dedicated to transforming the management of healthcare practices. As a subsidiary of Alkem Labs, the project's unwavering goal is to carry forward the company’s rich tradition of excellence and unwavering dedication to healthcare. This cutting-edge platform stands as an AI-driven, comprehensive solution that not only streamlines and elevates the patient experience but also empowers healthcare providers with state-of-the-art tools and technologies.",
    demo: "https://www.connect2clinic.com",
    gitHub: "",
    technologies: [
      "JavaScript",
      "React",
      "Redux-toolkit",
      "TailwindCSS",
      "BitBucket",
      "JIRA",
      "AWS",
    ],
    company: "Indus Net Technologies",
    duration: "1 year 1 months",
  },
  {
    img: "https://github.com/Swapnil1296/portfolio_images/blob/main/images/Screenshot%202024-04-15%20174029.png?raw=true",
    title: "Alkem Market Place",
    des: "Alkem Market Place, owned by Alkem Labs, is an online platform simplifying the ordering of in-stock medicines. Designed for ease, it offers a seamless ordering experience for both healthcare providers and patients. With real-time stock updates and a user-friendly interface, it ensures timely and reliable delivery, reflecting Alkem's commitment to modernizing healthcare.",
    demo: "https://alkemmarketplace.in/",
    gitHub: "",
    technologies: [
      "JavaScript",
      "React",
      "Redux-toolkit",
      "React-Bootstrap",
      "BitBucket",
      "NodeJs",
      "PostgreSQL",
      "ExpressJs",
      "AWS",
    ],
    company: "Indus Net Technologies",
    duration: "On Going",
  },

  {
    img: "https://github.com/Swapnil1296/portfolio_images/blob/main/meesho/landingpage.png?raw=true",
    title: "Meesho App",
    des: "Meesho is an e-commerce Indian website of wide range of apparel, cosmetics, household items, and many more categories",
    demo: "",
    live: "https://meesho-clone-xi.vercel.app/",
    gitHub: "https://github.com/Swapnil1296/Meesho-",
    technologies: [
      "HTML",
      "CSS",
      "JavaScript",
      "React",
      "Redux",
      "Material UI",
      "MongoDB",
      "Express.js",
      "Node.js",
      "NPM packeges - Dotenv, jsonwebtoken , bcryptjs",
    ],
    company: "Independent Developer",
    duration: "",
  },
  {
    img: "https://github.com/Swapnil1296/portfolio_images/blob/main/creado/Landing%20page.png?raw=true",
    title: "Creadobeauty",
    des: "CredoBeauty is an E-commerce platform,Where they are building a destination where one can find the most comprehensive collection of the most beautiful, safe and effective beauty products in the world. In this project we have tried to make a look alike clone of CredoBeauty. With our efforts and the technology stack, that we have learned so far in the masai school, we were able to clone the front end with high precision and quality.",
    demo: "",
    live: "https://luxury-otter-de9ba2.netlify.app/",
    gitHub: "https://github.com/Swapnil1296/creado",
    technologies: ["HTML", "CSS", "JavaScript", "Localstorage", "Bootstrap"],
    company: "Independent Developer",
    duration: "",
  },
  {
    img: "https://github.com/Swapnil1296/portfolio_images/blob/main/Groww/Landing%20page.png?raw=true",
    title: "Groww's Clone",
    des: "Groww is a website which let users to trade their money in different types of stock and share market.This is our team collaboration project at Full Stack-development bootcamp in Masai School.",
    demo: "",
    live: "https://angry-torvalds-f98880.netlify.app/",
    gitHub: "https://github.com/Swapnil1296/Groww-clone-frontend",
    technologies: [
      "HTML",
      "CSS",
      "JavaScript",
      "ExpressJs",
      "NodeJs",
      "MongoDB",
      "Mongoose",
    ],
    company: "Independent Developer",
    duration: "",
  },
];
